version: "3.3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "poetry install &&
               poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8000 &
           poetry run streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0"
    env_file:
      - .env

